name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v4

    - name: Install Python, pipenv and Pipfile packages
      uses: palewire/install-python-pipenv-pipfile@v3
      with:
        python-version: 3.x
