name: Update playlist

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0-12 * * *'
    - cron: '45 19-23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check Out Repo 
      uses: actions/checkout@v4
    
    - name: Download token.json
      run: echo ${{ secrets.YOUTUBE_TOKEN_FILE }} | base64 -d > token.json

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: pipenv
    
    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

    - name: Install dependencies
      run: pipenv install
    
    - name: Start XVFB
      run: Xvfb :99 &

    - name: Execute
      run: pipenv run main
      env:
        YOUTUBE_PLAYLIST_ID: ${{ secrets.YOUTUBE_PLAYLIST_ID }}
        MOVIE_LANGUAGE: JAPANESE
        DISPLAY: :99

    - name: Upload tmp folder
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: token.json
        path: token.json
