name: Update playlist

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0-12 * * *'
    - cron: '45 19-23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check Out Repo 
      uses: actions/checkout@v4
    
    - name: Download token.json
      run: echo ${{ secrets.YOUTUBE_TOKEN_FILE }} | base64 -d > token.json

    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install dependencies
      run: uv sync --dev

    - name: Execute
      run: uv run main.py
      env:
        YOUTUBE_PLAYLIST_ID: ${{ secrets.YOUTUBE_PLAYLIST_ID }}
        MOVIE_LANGUAGE: JAPANESE
        DISPLAY: :99

    - name: Upload tmp folder
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: token.json
        path: token.json
